cast (ID_ANOMALIA) as decimal(31,0) as ID_ANOMALIA ,
TIPO_ANOMALIA ,
STATO_ANOMALIA ,
to date (DATA_ORA_INIZIO) as DATA_ORA_INIZIO ,
to date (DATA_ORA_FINE) as DATA_ORA_FINE ,
cast (ID_RICHIESTA) as decimal(31,0) as ID_RICHIESTA 