cast (ID_SOSTA) as decimal(31,0) as ID_SOSTA ,
to date (DATA_ORA_SOSTA) as DATA_ORA_SOSTA ,
cast (NUM_LAT_SOSTA) as decimal(10,6) as NUM_LAT_SOSTA ,
cast (NUM_LONG_SOSTA) as decimal(10,6) as NUM_LONG_SOSTA ,
cast (QUALITA_GPS) as bigint as QUALITA_GPS ,
COD_PROVINCIA ,
DESC_VIA ,
COD_CAP ,
DESC_COMUNE ,
DESC_CATEG_STRADA ,
cast (ID_RICHIESTA) as decimal(31,0) as ID_RICHIESTA 