INSERT OVERWRITE TABLE %s.%s 
SELECT
dedup.ID_ANOMALIA,
dedup.TIPO_ANOMALIA,
dedup.STATO_ANOMALIA,
dedup.DATA_ORA_INIZIO,
dedup.DATA_ORA_FINE,
dedup.ID_RICHIESTA
FROM (
    SELECT *
    FROM
        %s.%s
    UNION ALL
    SELECT
        *
    FROM
        %s.%s ) as dedup
GROUP BY
dedup.ID_ANOMALIA,
dedup.TIPO_ANOMALIA,
dedup.STATO_ANOMALIA,
dedup.DATA_ORA_INIZIO,
dedup.DATA_ORA_FINE,
dedup.ID_RICHIESTA